In [1]:
import tensorflow as tf
import numpy as np 
import os 
import time
import re

# NGrams

In [2]:
# read the data  
text=open('qisasse_com.txt','rb').read().decode(encoding='utf-8')


In [3]:
import re
def preprocess(text):  
    text = re.sub(r'[^\w\s]', '', text)
    return "".join(text)


In [4]:
text=preprocess(text)

In [5]:
text[:250]

'قصة الملك وابنة الخادمة\nأراد أن يتزوج  فقرر أن يقيم حفلا يجمع فيه بنات القرية ليختار منهن فريسة احلامه  فتسارعت الفتيات لحضور الحفل\nكان هناك\nكان هناك ملك أراد أن يتزوج  فقرر أن يقيم حفلا يجمع فيه بنات القرية ليختار منهن فريسة احلامه  فتسارعت الفتيات '

In [6]:
# the unique characters in the file 
vocab=sorted(set(text))
print('{} unique characters'.format(len(vocab)))
vocab

199 unique characters


['\n',
 ' ',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 'A',
 'E',
 'G',
 'H',
 'I',
 'K',
 'M',
 'N',
 'S',
 'T',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 'ء',
 'آ',
 'أ',
 'ؤ',
 'إ',
 'ئ',
 'ا',
 'ب',
 'ة',
 'ت',
 'ث',
 'ج',
 'ح',
 'خ',
 'د',
 'ذ',
 'ر',
 'ز',
 'س',
 'ش',
 'ص',
 'ض',
 'ط',
 'ظ',
 'ع',
 'غ',
 'ـ',
 'ف',
 'ق',
 'ك',
 'ل',
 'م',
 'ن',
 'ه',
 'و',
 'ى',
 'ي',
 '٠',
 '١',
 '٢',
 '٣',
 '٤',
 '٥',
 '٩',
 'ٹ',
 'پ',
 'ک',
 'ں',
 'ھ',
 'ہ',
 'ۃ',
 'ی',
 'ې',
 'ﺀ',
 'ﺁ',
 'ﺃ',
 'ﺄ',
 'ﺇ',
 'ﺈ',
 'ﺌ',
 'ﺍ',
 'ﺎ',
 'ﺏ',
 'ﺐ',
 'ﺑ',
 'ﺒ',
 'ﺓ',
 'ﺔ',
 'ﺕ',
 'ﺖ',
 'ﺗ',
 'ﺘ',
 'ﺛ',
 'ﺜ',
 'ﺝ',
 'ﺟ',
 'ﺠ',
 'ﺡ',
 'ﺢ',
 'ﺣ',
 'ﺤ',
 'ﺧ',
 'ﺨ',
 'ﺩ',
 'ﺪ',
 'ﺫ',
 'ﺬ',
 'ﺭ',
 'ﺮ',
 'ﺯ',
 'ﺰ',
 'ﺱ',
 'ﺲ',
 'ﺳ',
 'ﺴ',
 'ﺷ',
 'ﺸ',
 'ﺻ',
 'ﺼ',
 'ﺽ',
 'ﺿ',
 'ﻀ',
 'ﻂ',
 'ﻃ',
 'ﻄ',
 'ﻆ',
 'ﻇ',
 'ﻈ',
 'ﻊ',
 'ﻋ',
 'ﻌ',
 'ﻍ',
 'ﻏ',
 'ﻐ',
 'ﻒ',
 'ﻓ',
 'ﻔ',
 'ﻗ',
 'ﻘ

In [7]:
# The i:j part of the comprehension creates a new key-value pair in the dictionary, with the key being the element j and the value being the index i.
char_idx={j:i for i,j in enumerate(vocab)}
idx_char=np.array(vocab)
text_as_int=np.array([char_idx[c] for c in text])


In [8]:
char_idx

{'\n': 0,
 ' ': 1,
 '0': 2,
 '1': 3,
 '2': 4,
 '3': 5,
 '4': 6,
 '5': 7,
 '6': 8,
 '7': 9,
 '8': 10,
 '9': 11,
 'A': 12,
 'E': 13,
 'G': 14,
 'H': 15,
 'I': 16,
 'K': 17,
 'M': 18,
 'N': 19,
 'S': 20,
 'T': 21,
 '_': 22,
 'a': 23,
 'b': 24,
 'c': 25,
 'd': 26,
 'e': 27,
 'f': 28,
 'g': 29,
 'h': 30,
 'i': 31,
 'k': 32,
 'l': 33,
 'm': 34,
 'n': 35,
 'o': 36,
 'p': 37,
 'q': 38,
 'r': 39,
 's': 40,
 't': 41,
 'u': 42,
 'v': 43,
 'w': 44,
 'x': 45,
 'y': 46,
 'z': 47,
 'ء': 48,
 'آ': 49,
 'أ': 50,
 'ؤ': 51,
 'إ': 52,
 'ئ': 53,
 'ا': 54,
 'ب': 55,
 'ة': 56,
 'ت': 57,
 'ث': 58,
 'ج': 59,
 'ح': 60,
 'خ': 61,
 'د': 62,
 'ذ': 63,
 'ر': 64,
 'ز': 65,
 'س': 66,
 'ش': 67,
 'ص': 68,
 'ض': 69,
 'ط': 70,
 'ظ': 71,
 'ع': 72,
 'غ': 73,
 'ـ': 74,
 'ف': 75,
 'ق': 76,
 'ك': 77,
 'ل': 78,
 'م': 79,
 'ن': 80,
 'ه': 81,
 'و': 82,
 'ى': 83,
 'ي': 84,
 '٠': 85,
 '١': 86,
 '٢': 87,
 '٣': 88,
 '٤': 89,
 '٥': 90,
 '٩': 91,
 'ٹ': 92,
 'پ': 93,
 'ک': 94,
 'ں': 95,
 'ھ': 96,
 'ہ': 97,
 'ۃ': 98,
 'ی': 99,
 'ې': 100

In [9]:
text_as_int[:255]

array([76, 68, 56,  1, 54, 78, 79, 78, 77,  1, 82, 54, 55, 80, 56,  1, 54,
       78, 61, 54, 62, 79, 56,  0, 50, 64, 54, 62,  1, 50, 80,  1, 84, 57,
       65, 82, 59,  1,  1, 75, 76, 64, 64,  1, 50, 80,  1, 84, 76, 84, 79,
        1, 60, 75, 78, 54,  1, 84, 59, 79, 72,  1, 75, 84, 81,  1, 55, 80,
       54, 57,  1, 54, 78, 76, 64, 84, 56,  1, 78, 84, 61, 57, 54, 64,  1,
       79, 80, 81, 80,  1, 75, 64, 84, 66, 56,  1, 54, 60, 78, 54, 79, 81,
        1,  1, 75, 57, 66, 54, 64, 72, 57,  1, 54, 78, 75, 57, 84, 54, 57,
        1, 78, 60, 69, 82, 64,  1, 54, 78, 60, 75, 78,  0, 77, 54, 80,  1,
       81, 80, 54, 77,  0, 77, 54, 80,  1, 81, 80, 54, 77,  1, 79, 78, 77,
        1, 50, 64, 54, 62,  1, 50, 80,  1, 84, 57, 65, 82, 59,  1,  1, 75,
       76, 64, 64,  1, 50, 80,  1, 84, 76, 84, 79,  1, 60, 75, 78, 54,  1,
       84, 59, 79, 72,  1, 75, 84, 81,  1, 55, 80, 54, 57,  1, 54, 78, 76,
       64, 84, 56,  1, 78, 84, 61, 57, 54, 64,  1, 79, 80, 81, 80,  1, 75,
       64, 84, 66, 56,  1

In [10]:
# show ho the first 20 chararacters from the text are mapped to integers
print('{}--------- characters mapped to int--------> {}'.format(repr(text[:13]),text_as_int[:13]))

'قصة الملك واب'--------- characters mapped to int--------> [76 68 56  1 54 78 79 78 77  1 82 54 55]


In [11]:
# the maximum lenght sentence for the single input in characters
seq_length=100
# create training exaples / targets
char_dataset=tf.data.Dataset.from_tensor_slices(text_as_int)


In [12]:
# to make the input the same size in the character  and add the one character to make the  traget 
squences=char_dataset.batch(seq_length+1,drop_remainder=True)


function returns a printable representation of the given object.


In [13]:
for item in squences.take(5):
  print(repr(''.join(idx_char[item.numpy()])),item,len(item))

'قصة الملك وابنة الخادمة\nأراد أن يتزوج  فقرر أن يقيم حفلا يجمع فيه بنات القرية ليختار منهن فريسة احلام' tf.Tensor(
[76 68 56  1 54 78 79 78 77  1 82 54 55 80 56  1 54 78 61 54 62 79 56  0
 50 64 54 62  1 50 80  1 84 57 65 82 59  1  1 75 76 64 64  1 50 80  1 84
 76 84 79  1 60 75 78 54  1 84 59 79 72  1 75 84 81  1 55 80 54 57  1 54
 78 76 64 84 56  1 78 84 61 57 54 64  1 79 80 81 80  1 75 64 84 66 56  1
 54 60 78 54 79], shape=(101,), dtype=int32) 101
'ه  فتسارعت الفتيات لحضور الحفل\nكان هناك\nكان هناك ملك أراد أن يتزوج  فقرر أن يقيم حفلا يجمع فيه بنات ا' tf.Tensor(
[81  1  1 75 57 66 54 64 72 57  1 54 78 75 57 84 54 57  1 78 60 69 82 64
  1 54 78 60 75 78  0 77 54 80  1 81 80 54 77  0 77 54 80  1 81 80 54 77
  1 79 78 77  1 50 64 54 62  1 50 80  1 84 57 65 82 59  1  1 75 76 64 64
  1 50 80  1 84 76 84 79  1 60 75 78 54  1 84 59 79 72  1 75 84 81  1 55
 80 54 57  1 54], shape=(101,), dtype=int32) 101
'لقرية ليختار منهن فريسة احلامه  فتسارعت الفتيات لحضور الحفل\nكان هناك ملك أراد أن يت

In [14]:
def split_input_target(chunk):
    input_text=chunk[:-1]
    traget_text=chunk[1:]
    return input_text,traget_text

In [15]:
dataset=squences.map(split_input_target)

In [16]:
for i ,j in dataset.take(1):
    print('input data','',''.join(idx_char[i.numpy()]))
    print('Taraget data','',''.join(idx_char[j.numpy()]))

input data  قصة الملك وابنة الخادمة
أراد أن يتزوج  فقرر أن يقيم حفلا يجمع فيه بنات القرية ليختار منهن فريسة احلا
Taraget data  صة الملك وابنة الخادمة
أراد أن يتزوج  فقرر أن يقيم حفلا يجمع فيه بنات القرية ليختار منهن فريسة احلام


In [17]:
len(dataset)

15155

In [18]:
batch_size=64
BUFFER_SIZE=10000
# make the  dataset shuffle  and put in the batch
dataset=dataset.shuffle(BUFFER_SIZE).batch(batch_size,drop_remainder=True)
dataset

<BatchDataset element_spec=(TensorSpec(shape=(64, 100), dtype=tf.int32, name=None), TensorSpec(shape=(64, 100), dtype=tf.int32, name=None))>

In [19]:
vocb_size=len(vocab)
embedding_dim=256
ruu_units=1024

In [20]:
def build_model(vocb_size,embedding_dim,ruu_units,batch_size):
    model=tf.keras.Sequential([
      tf.keras.layers.Embedding(vocb_size,embedding_dim,batch_input_shape=[batch_size,None]),
      tf.keras.layers.GRU(ruu_units,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'),
      tf.keras.layers.Dense(vocb_size)])
    return model

In [21]:
Model=build_model(vocb_size=len(vocab),embedding_dim=embedding_dim,ruu_units=ruu_units,batch_size=batch_size)

In [22]:
Model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (64, None, 256)           50944     
                                                                 
 gru (GRU)                   (64, None, 1024)          3938304   
                                                                 
 dense (Dense)               (64, None, 199)           203975    
                                                                 
Total params: 4,193,223
Trainable params: 4,193,223
Non-trainable params: 0
_________________________________________________________________


In [23]:
# Use this crossentropy loss function when there are two or more label classes.
def loss(labels,logits):
    return tf.keras.losses.sparse_categorical_crossentropy(labels,logits,from_logits=True)

In [24]:
Model.compile(optimizer = 'adam',loss=loss)


In [ ]:
history=Model.fit(dataset,epochs=10) 

Epoch 1/10
  9/236 [>.............................] - ETA: 11:14 - loss: 4.8915